/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;




import java.awt.print.PrinterException;

import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nico
 */
public class PuntoVenta extends javax.swing.JPanel {
    static double sumaTotal=0;
    

    
    

    
    
    

    /**
     * Creates new form PuntoVenta
     */
    public PuntoVenta() {
        initComponents();
    
    }
    

    public void añadirTabla(String Nombre, Double Precio) {

        String cantidad = JOptionPane.showInputDialog("Introduce la cantidad");
        Double totalCantidad = Double.valueOf(cantidad);
        Double totalPrecio = Precio * totalCantidad;
        sumaTotal=sumaTotal+totalPrecio;

  

        DefaultTableModel dt = (DefaultTableModel) tblTablaProductos.getModel();
        
        
        lblTotal2.setText(String.valueOf(sumaTotal));

        Vector v = new Vector();
        v.add(Nombre);
        v.add(totalCantidad);
        v.add(totalPrecio);
        dt.addRow(v);
        
        

    }

   /* public void calcularCarrito() {

        int contador = tblTablaProductos.getRowCount();
        double total = 0;
        for (int i = 0; i < contador; i++) {
            double value = Double.valueOf(tblTablaProductos.getValueAt(i, 2).toString());
            total += value;

        }

        DecimalFormat df = new DecimalFormat("00.00");
        String d1 = df.format(total);
        lblTotal.setText(d1);
        
        

    }
    */

    public void imprimirTicket() {

        try {
            txtFactura.setText("               DeliBurguer Shop \n");
            txtFactura.setText(txtFactura.getText() + "\t3/ Badajoz, \n");
            txtFactura.setText(txtFactura.getText() + "\tMadrid, San Fernando de Henares, \n");
            txtFactura.setText(txtFactura.getText() + "\t+633 929 079, \n");
            txtFactura.setText(txtFactura.getText() + "----------------------------------------------------------------\n");
            txtFactura.setText(txtFactura.getText() + " Producto \tCantidad \tPrecio \n");
            txtFactura.setText(txtFactura.getText() + "----------------------------------------------------------------\n");

            for (int i = 0; i < tblTablaProductos.getRowCount(); i++) {
                System.out.println("holi");
                String productoTicket = tblTablaProductos.getValueAt(i, 0).toString();
                String cantidadTicket = tblTablaProductos.getValueAt(i, 1).toString();
                String precioTicket = tblTablaProductos.getValueAt(i, 2).toString();

                txtFactura.setText(txtFactura.getText() + productoTicket + "\t" + cantidadTicket + "\t" + precioTicket + " \n");

            }
            txtFactura.setText(txtFactura.getText() + "----------------------------------------------------------------\n");
            txtFactura.setText(txtFactura.getText() + "Total :\t" + lblTotal2.getText() + "\n");
            txtFactura.setText(txtFactura.getText() + "Pagado :\t" + lblPagado2.getText() + "\n");
            txtFactura.setText(txtFactura.getText() + "Cambio :\t" + lblCambio2.getText() + "\n");
            txtFactura.setText(txtFactura.getText() + "====================================\n");
            txtFactura.setText(txtFactura.getText() + "                     Vuelva pronto!" + "\n");
            txtFactura.setText(txtFactura.getText() + "----------------------------------------------------------------\n");
            txtFactura.setText(txtFactura.getText() + "                     Software por Nico ehe" + "\n");

            txtFactura.print();

        } catch (PrinterException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        lblTotal2 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        lblCambio2 = new javax.swing.JLabel();
        lblPagado = new javax.swing.JLabel();
        lblPagado2 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JToggleButton();
        btnDesconectar = new javax.swing.JButton();
        btnVolverMesa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFactura = new javax.swing.JTextArea();
        pnlProductos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaProductos = new javax.swing.JTable();
        btnFiltroBebidas = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        btnCocacola = new javax.swing.JButton();
        btnFanta = new javax.swing.JButton();
        btnNestea = new javax.swing.JButton();
        btnImprimirTicket = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(1440, 950));
        setPreferredSize(new java.awt.Dimension(1440, 950));

        jPanel1.setBackground(new java.awt.Color(23, 13, 13));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 950));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 950));

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotal.setText("Total :");

        lblTotal2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTotal2.setText("0");

        lblCambio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCambio.setText("Cambio:");

        lblCambio2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCambio2.setText("0");

        lblPagado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPagado.setText("Pagado:");

        lblPagado2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblPagado2.setText("0");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPagado)
                            .addComponent(lblTotal)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblCambio)))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPagado2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnCalcular))
                    .addComponent(lblTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCambio2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal)
                    .addComponent(lblTotal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPagado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcular))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPagado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCambio2)
                    .addComponent(lblCambio))
                .addGap(42, 42, 42))
        );

        btnDesconectar.setBackground(new java.awt.Color(73, 84, 81));
        btnDesconectar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnDesconectar.setForeground(new java.awt.Color(229, 218, 218));
        btnDesconectar.setText("Desconectar");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });

        btnVolverMesa.setBackground(new java.awt.Color(73, 84, 81));
        btnVolverMesa.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnVolverMesa.setForeground(new java.awt.Color(229, 218, 218));
        btnVolverMesa.setText("Mesas");
        btnVolverMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMesaActionPerformed(evt);
            }
        });

        txtFactura.setColumns(20);
        txtFactura.setRows(5);
        jScrollPane2.setViewportView(txtFactura);

        javax.swing.GroupLayout pnlProductosLayout = new javax.swing.GroupLayout(pnlProductos);
        pnlProductos.setLayout(pnlProductosLayout);
        pnlProductosLayout.setHorizontalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
        pnlProductosLayout.setVerticalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_dashboard.png"))); // NOI18N

        tblTablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblTablaProductos);

        btnFiltroBebidas.setText("Bebidas");
        btnFiltroBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroBebidasActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Todos los productos");

        jToggleButton3.setText("Comidas");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Postres");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        btnCocacola.setBackground(new java.awt.Color(66, 35, 9));
        btnCocacola.setText("Cocacola");
        btnCocacola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocacolaActionPerformed(evt);
            }
        });

        btnFanta.setBackground(new java.awt.Color(237, 222, 32));
        btnFanta.setText("Fanta");
        btnFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFantaActionPerformed(evt);
            }
        });

        btnNestea.setBackground(new java.awt.Color(247, 158, 32));
        btnNestea.setText("Nestea");
        btnNestea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNesteaActionPerformed(evt);
            }
        });

        btnImprimirTicket.setText("Imprimir Ticket");
        btnImprimirTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jToggleButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(btnFiltroBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))))
                .addGap(92, 92, 92)
                .addComponent(pnlProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(btnCocacola, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnFanta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnNestea, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnImprimirTicket)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVolverMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnFiltroBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnFanta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNestea, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCocacola, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnImprimirTicket)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNesteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNesteaActionPerformed
        // TODO add your handling code here:
        añadirTabla("Nestea",5.00);
    }//GEN-LAST:event_btnNesteaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        double pagado = Double.valueOf(lblPagado2.getText());
        
        double cambio = pagado-sumaTotal;
        lblCambio2.setText(String.valueOf(cambio)+"€");
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        // TODO add your handling code here:
        Principal.login.setVisible(true);
        Principal.puntoventa.setVisible(false);
    }//GEN-LAST:event_btnDesconectarActionPerformed

    private void btnCocacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocacolaActionPerformed
        // TODO add your handling code here:
        añadirTabla("Coca-Cola",2.00);
    }//GEN-LAST:event_btnCocacolaActionPerformed

    private void btnFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFantaActionPerformed
        // TODO add your handling code here:
        añadirTabla("Fanta",2.00);
    }//GEN-LAST:event_btnFantaActionPerformed

    private void btnVolverMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMesaActionPerformed
        // TODO add your handling code here:
        Principal.puntoventa.setVisible(false);
        Principal.mesas.setVisible(true);
    }//GEN-LAST:event_btnVolverMesaActionPerformed

    private void btnFiltroBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroBebidasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnFiltroBebidasActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void btnImprimirTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirTicketActionPerformed
        // TODO add your handling code here:
        imprimirTicket();
    }//GEN-LAST:event_btnImprimirTicketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalcular;
    private javax.swing.JButton btnCocacola;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnFanta;
    private javax.swing.JToggleButton btnFiltroBebidas;
    private javax.swing.JToggleButton btnImprimirTicket;
    private javax.swing.JButton btnNestea;
    private javax.swing.JButton btnVolverMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblCambio2;
    private javax.swing.JLabel lblPagado;
    private javax.swing.JTextField lblPagado2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JPanel pnlProductos;
    protected static javax.swing.JTable tblTablaProductos;
    private javax.swing.JTextArea txtFactura;
    // End of variables declaration//GEN-END:variables
}
